# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    default_manager: mongodb
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        candidate:
            properties:
                email: ~
                firstName: ~
                lastName: ~
                dateOfBirth: ~
                cvFileName: ~
            persistence:
                driver: orm
                model: App\Entity\Candidate